url: https://lareinatech.com

title: Lareina

keywords: Lareina

description: Lareina

address: No.7, Xi’an Road, Shawan Town, Panyu District, Guangzhou, China, 510000

email: support@lareinatech.com

exclude:
  - README.md
  - style.css
