url: https://www.88pvc.com

title: Lareina

keywords: Lareina

description: Lareina

address: No.7, Xi’an Road, Shawan Town, Panyu District, Guangzhou, China, 510000

tel: +86-020-34833982

email: contact@flexwarm.com

facebook: https://www.facebook.com/flexwarm/

twitter: https://twitter.com/getflexwarm

linkedin: https://www.linkedin.com/company/flexwarm/

youtube: https://www.youtube.com/channel/UC0NXHUd6SszgwJ5isP_gJOQ/

exclude:
  - README.md
  - style.css
